BROKER_URL: localhost
BROKER_PORT: 1883
TOPIC: site1/#
QOS: 0
NR_OF_MESSAGES: 1000
PUBLISH_INTERVAL: 5
CLEAN_START: True
SESSION_EXPIRY_INTERVAL: 0
TLS_ENABLED: False
REATTEMPTS: -1
TESTDATA_PATH: testdata/aadi
CLIENT_ID: subscriber
